### ISSUE TITLE
No se muestra la paginación

### ISSUE THREAD

**Issue by nicolasguzca** [wasico/wasi-connector#2]
Hola, actualmente no se muestra la paginación en las propiedades. Toca ponerlo con un shortcode o es automático?

Gracias y saludos

**Comment by nicolasguzca** [comment]
Buenos días, ya actualicé a la ultima versión y sigue sin salir la paginación. Toca editar algo o poner un shortcode para que salga?

**Comment by jep82** [comment]
Tengo el mismo problema, en la última versión no muestra la paginación, de casualidad alguien tiene una versión anterior donde si funcione? la versión que está en el ejemplo (https://demo.wasi.co/properties/) podrían poner un enlace para su descarga?
